---
title: "References"
---

<style>
body {
text-align: justify;
font-family: Times;
font-size: 2em
}
</style>

Broman, K. W., and S. Sen, 2009 A Guide to QTL Mapping with R/qtl, Vol. 46. Springer, New York.

Broman, K. W., H. Wu, S. Sen, and G. A. Churchill, 2003 R/qtl: QTL mapping in experimental crosses. Bioinformatics 19: 889–890.

Fishman, L.A., Kelly, J., Morgan, E., Willis, J.H., 2001 A genetic map in the Mimulus guttatus species complex reveals transmission ratio distortion due to heterospecific interactions. Genetics 159: 1701-1716.

Fishman, L. A., and J. H. Willis, 2001 Evidence for Dobzhansky-Muller Inteincompatibilities contributing to the sterility of hybrids between Mimulus guttatus and M. nasutus. Evolution 55: 1932–1942

Kosambi, D.D., 1944 The estimation of map distance from recombination values. Annuaire of Eugenetics 12:172-175.

Margarido, G.R., Souza, A.P, Garcia, A.A.F., 2007 OneMap: software for genetic mapping in outcrossing species. Hereditas 144:78-79.

Voorrips, R.E., 2002 MapChart: software for the graphical presentation of linkage maps and QTLs. J. of Hered. 93: 77-78.

Wu, R., Ma, C.-X., Painter, I. and Zeng, Z.-B. (2002) Simultaneous maximum likelihood estimation of linkage and linkage phases in outcrossing species. Theoretical Population Biology 61: 349-363.